CREATE SCHEMA featureFlags__featureFlagsConfig_Setup_usp AUTHORIZATION dbo;
GO
EXECUTE sp_addextendedproperty @name = N'tSQLt.TestClass', @value = 1, @level0type = N'SCHEMA', @level0name = N'featureFlags__featureFlagsConfig_Setup_usp';
GO
/****
Script generated by cookiecutter.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
Changes to this code will not be preserved if regenerated.
****/
/****
Suggestion: move this file to the Security folder of your
Visual Studio dbproj for consistency with standard project
layout.
****/
