CREATE PROCEDURE [featureFlags__featureFlagsConfig_Setup_usp].[test Not-Specified Values Persist Unchanged]
AS
BEGIN
	--ASSEMBLE
	IF OBJECT_ID('[featureFlags__featureFlagsConfig_Setup_usp].ACTUAL') IS NOT NULL DROP TABLE [featureFlags__featureFlagsConfig_Setup_usp].ACTUAL;
	IF OBJECT_ID('[featureFlags__featureFlagsConfig_Setup_usp].EXPECTED') IS NOT NULL DROP TABLE [featureFlags__featureFlagsConfig_Setup_usp].EXPECTED;
	DELETE [featureFlags].[featureFlagsConfig];
	EXECUTE [featureFlags].[featureFlagsConfig_Setup_usp] @OptionalFeature1 = 1, @OptionalFeature2 = 0;

	--ACT
	EXECUTE [featureFlags].[featureFlagsConfig_Setup_usp];

	SELECT 
	[Id]
	,[OptionalFeature1]
	,[OptionalFeature2]
	INTO [featureFlags__featureFlagsConfig_Setup_usp].ACTUAL
	FROM [featureFlags].[featureFlagsConfig];

	--ASSERT
	CREATE TABLE [featureFlags__featureFlagsConfig_Setup_usp].EXPECTED (
		[Id] [INT]
		,[OptionalFeature1] [BIT]
		,[OptionalFeature2] [BIT]
	);
	INSERT INTO [featureFlags__featureFlagsConfig_Setup_usp].EXPECTED (
		[Id]
		,[OptionalFeature1]
		,[OptionalFeature2]
	) VALUES (
		1, 1, 0
	);

	EXECUTE [tSQLt].AssertEqualsTable @Expected = '[featureFlags__featureFlagsConfig_Setup_usp].EXPECTED', @Actual = '[featureFlags__featureFlagsConfig_Setup_usp].ACTUAL';

END

/****
Script generated by cookiecutter, for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Verify the object being selected from in the
Act section. It defaults to your object under test.
****/
