CREATE PROCEDURE [featureFlags__featureFlagsConfig].[test Check constraint prevents more than one row existing]
AS
BEGIN

	--ASSEMBLE
	DELETE [featureFlags].[featureFlagsConfig];
	INSERT INTO [featureFlags].[featureFlagsConfig] ([Id]) VALUES (1);

	--ACT
	DECLARE @Message NVARCHAR(4000) = N'The INSERT statement conflicted with the CHECK constraint "ck_featureFlags_featureFlagsConfig_Id". The conflict occurred in database "' + DB_NAME() + '", table "featureFlags.featureFlagsConfig", column ''Id''.';
	EXECUTE tSQLt.ExpectException @ExpectedMessage = @Message;

	--ASSERT
	INSERT INTO [featureFlags].[featureFlagsConfig] ([Id]) VALUES (2);

END

/****
Script generated by cookiecutter, for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Update the @ExpectedMessage once you know
your error message.
****/
